Repository puppetlabs/facter-ng, pull requests merged in 2020-03, with the labels that each got.

#420 (FACT-2498) Internal fact loader should only load facts once
  .rubocop_todo.yml
  lib/framework/core/fact_loaders/internal_fact_loader.rb
  spec/framework/core/fact_loaders/internal_fact_loader_spec.rb
Labels: bugfix

#398 (FACT-2231) Add AIX mountpoints fact
  lib/facts/aix/mountpoints.rb
  lib/resolvers/aix/mountpoints.rb
  spec/facter/facts/aix/mountpoints_spec.rb
  spec/facter/resolvers/aix/mountpoints_spec.rb
  spec/fixtures/df
  spec/fixtures/mount
Labels: feature

#415 (FACT-2500) Fix RSpec/AnyInstance offences
  .rubocop_todo.yml
  spec/custom_facts/core/aggregate_spec.rb
  spec/facter/facter_spec.rb
  spec/facter/resolvers/solaris/solaris_release_resolver_spec.rb
  spec/facter/resolvers/utils/windows/network_utils_spec.rb
  spec/facter/resolvers/windows/dmi_bios_resolver_spec.rb
  spec/facter/resolvers/windows/dmi_computersystem_resolver_spec.rb
  spec/facter/resolvers/windows/identity_resolver_spec.rb
  spec/facter/resolvers/windows/kernel_resolver_spec.rb
  spec/facter/resolvers/windows/memory_resolver_spec.rb
  spec/facter/resolvers/windows/networking_resolver_spec.rb
  spec/facter/resolvers/windows/processors_resolver_spec.rb
  spec/facter/resolvers/windows/system32_resolver_spec.rb
  spec/facter/resolvers/windows/uptime_resolver_spec.rb
  spec/facter/resolvers/windows/virtualization_resolver_spec.rb
  spec/facter/resolvers/windows/win_os_description_resolver_spec.rb
  spec/framework/core/fact_loaders/class_discoverer_spec.rb
  spec/framework/core/fact_manager_spec.rb
  spec/framework/core/options/options_validator_spec.rb
  spec/mocks/util.rb
Labels: maintenance
