Repository puppetlabs/facter-ng, pull requests merged in 2020-06, with the labels that each got.

#531 (FACT-2607) Add Openvz detector
  lib/facts/linux/virtual.rb
  lib/resolvers/open_vz.rb
  spec/facter/facts/linux/virtual_spec.rb
  spec/facter/resolvers/open_vz_spec.rb
  spec/fixtures/proc_self_status
Labels: feature

#532 (FACT-2245) Add xen resolver
  lib/facts/linux/virtual.rb
  lib/resolvers/xen.rb
  spec/facter/facts/linux/virtual_spec.rb
  spec/facter/resolvers/xen_spec.rb
Labels: feature

#534 (FACT-2609) Add lspci resolver
  lib/facts/linux/virtual.rb
  lib/resolvers/lspci.rb
  spec/facter/facts/linux/virtual_spec.rb
  spec/facter/resolvers/lspci_spec.rb
  spec/facter/resolvers/vmware_spec.rb
  spec/fixtures/lspci_aws
  spec/fixtures/lspci_vmware
Labels: feature

#535 (FACT-2608) Add is_virtual fact
  lib/facts/linux/is_virtual.rb
  spec/facter/facts/linux/is_virtual_spec.rb
Labels: feature

#542 Test commit message action
  .github/workflows/checks.yaml
  tasks/commits.rake
Labels: maintenance

#536 (FACT-2635) Incorrect output for non existing fact
  .rubocop_todo.yml
  lib/facter.rb
  lib/framework/core/fact/internal/internal_fact_manager.rb
  lib/framework/formatters/legacy_fact_formatter.rb
  lib/framework/parsers/query_parser.rb
  spec/facter/facter_spec.rb
  spec/facter/query_parser_spec.rb
  spec/framework/core/fact/internal/internal_fact_manager_spec.rb
  tasks/commits.rake
Labels: bugfix

#545 (FACT-2651) Fix --list-cache-groups when there are multiple arguments before it
  .github/workflows/unit_tests.yaml
  bin/facter
  bin/facter-ng
  lib/framework/cli/cli_launcher.rb
  spec/framework/cli/cli_launcher_spec.rb
Labels: bugfix

#539 Use proper encoding
  lib/resolvers/macosx/system_profiler_resolver.rb
Labels: bugfix

#543 FACT-2650 Fix bug when loading external facts
  lib/custom_facts/util/loader.rb
  spec/custom_facts/util/loader_spec.rb
Labels: bugfix

#519 (FACT-2600) Run acceptance tests on Windows
  .github/actions/presuite.rb
  .github/workflows/acceptance_tests.yml
Labels: feature

#547 (maint) Only run code coverage on master.
  .github/workflows/checks.yaml
  .github/workflows/coverage.yaml
Labels: bugfix

#548 (maint) Updated Changelog for 4.0.26
  CHANGELOG.md
Labels: maintenance

#541 (FACT-2619) External facts cache
  .rubocop.yml
  .rubocop_todo.yml
  lib/custom_facts/util/collection.rb
  lib/custom_facts/util/config.rb
  lib/custom_facts/util/directory_loader.rb
  lib/custom_facts/util/fact.rb
  lib/custom_facts/util/resolution.rb
  lib/framework/core/cache_manager.rb
  lib/framework/core/fact/external/external_fact_manager.rb
  lib/framework/core/fact_loaders/external_fact_loader.rb
  lib/framework/parsers/query_parser.rb
  lib/models/loaded_fact.rb
  lib/models/resolved_fact.rb
  lib/models/searched_fact.rb
  spec/custom_facts/util/collection_spec.rb
  spec/custom_facts/util/directory_loader_spec.rb
  spec/facter/cache_manager_spec.rb
  spec/facter/query_parser_spec.rb
  spec/framework/core/fact/external/external_fact_manager_spec.rb
  spec/framework/core/fact_loaders/external_fact_loader_spec.rb
  spec/mocks/util.rb
Labels: feature

#550 (maint) Lock rubocop-rspec
  facter.gemspec
Labels: maintenance

#551 (maint) update rtc-action to 0.2.0
  .github/workflows/checks.yaml
Labels: maintenance

#552 (FACT-2662) Relax rubocop-rspec dependency and fix offences
  facter.gemspec
  spec/custom_facts/core/execution/fact_manager_spec.rb
Labels: maintenance

#544 (FACT-2620) Add EC2 facts for linux
  .rubocop_todo.yml
  lib/facts/linux/ec2_metadata.rb
  lib/facts/linux/ec2_userdata.rb
  lib/facts/linux/is_virtual.rb
  lib/facts/linux/virtual.rb
  lib/facts_utils/hypervisors.rb
  lib/resolvers/ec2.rb
  spec/facter/facts/linux/ec2_metadata_spec.rb
  spec/facter/facts/linux/ec2_userdata_spec.rb
  spec/facter/resolvers/ec2_spec.rb
Labels: feature

#546 (FACT-2654) Add ec2 facts for Windows
  lib/facts/windows/ec2_metadata.rb
  lib/facts/windows/ec2_userdata.rb
  spec/facter/facts/windows/ec2_metadata_spec.rb
  spec/facter/facts/windows/ec2_userdata_spec.rb
Labels: feature

#549 (FACT-2638) Use puppet AIO VERSION file to specify AIO version
  .github/workflows/checks.yaml
  lib/facts/aix/aio_agent_version.rb
  lib/facts/linux/aio_agent_version.rb
  lib/facts/macosx/aio_agent_version.rb
  lib/facts/solaris/aio_agent_version.rb
  lib/facts/windows/aio_agent_version.rb
  lib/resolvers/aio_agent_version.rb
  lib/resolvers/windows/aio_agent_version.rb
  spec/facter/facts/aix/aio_agent_version_spec.rb
  spec/facter/facts/linux/aio_agent_version_spec.rb
  spec/facter/facts/macosx/aio_agent_version_spec.rb
  spec/facter/facts/solaris/aio_agent_version_spec.rb
  spec/facter/resolvers/aio_agent_version_spec.rb
  spec/facter/resolvers/windows/aio_agent_version_spec.rb
  spec/mocks/win32_mock.rb
  spec/mocks/win32_registry_error_mock.rb
Labels: feature

#553 (maint) Add FreeBSD disks and partitions facts
  lib/facts/freebsd/disks.rb
  lib/facts/freebsd/partitions.rb
  lib/resolvers/freebsd/geom_resolver.rb
  spec/facter/facts/freebsd/disks_spec.rb
  spec/facter/facts/freebsd/partitions_spec.rb
  spec/facter/resolvers/freebsd/geom_resolver_spec.rb
  spec/fixtures/kern.geom.confxml
Labels: feature

#555 FACT-2663 Use the provided beaker.gem and updated facter branch for acceptance tests
  .github/actions/presuite.rb
  .github/workflows/acceptance_tests.yml
Labels: maintenance

#556 Fix master
  lib/resolvers/ec2.rb
  spec/facter/resolvers/ec2_spec.rb
Labels: maintenance
