Repository puppetlabs/facter-ng, pull requests merged in 2020-05, with the labels that each got.

#492 (maint) Add change log for release 4.0.20
  CHANGELOG.md
  Rakefile
  spec/facter/resolvers/utils/windows/network_utils_spec.rb
Labels: maintenance

#488 (FACT-2557) Add rake task for generating list of facts for specified OS
  lib/framework/core/fact_loaders/internal_fact_loader.rb
  tasks/fact_list_generator.rake
Labels: feature

#493 (maint) Fix master branch
  lib/facter.rb
Labels: maintenance

#483 (FACT-2235) Add Aix processors fact
  lib/facts/aix/processors/count.rb
  lib/facts/aix/processors/isa.rb
  lib/facts/aix/processors/models.rb
  lib/facts/aix/processors/speed.rb
  lib/resolvers/aix/processors.rb
  spec/facter/facts/aix/processors/count_spec.rb
  spec/facter/facts/aix/processors/isa_spec.rb
  spec/facter/facts/aix/processors/models_spec.rb
  spec/facter/facts/aix/processors/speed_spec.rb
  spec/facter/resolvers/aix/processors_spec.rb
  spec/fixtures/processors_cuat
  spec/fixtures/processors_cudv
  spec/fixtures/processors_pddv
Labels: feature

#491 (FACT-2515) Define custom fact groups in facter.conf
  facter.conf
  lib/facter.rb
  lib/framework/config/config_reader.rb
  lib/framework/config/fact_groups.rb
  lib/framework/core/cache_manager.rb
  lib/framework/core/options/config_file_options.rb
  lib/framework/core/options/option_store.rb
  spec/facter/facter_spec.rb
  spec/framework/config/config_reader_spec.rb
  spec/framework/config/fact_groups_spec.rb
  spec/framework/core/options/option_store_spec.rb
Labels: feature

#494 (maint) Correctly initialise logger in ODMQuery
  lib/resolvers/aix/utils/odm_query.rb
Labels: maintenance

#495 (maint) Fix rspec warnings
  spec/facter/resolvers/aix/processors_spec.rb
  spec/facter/resolvers/solaris/solaris_zone_name_spec.rb
  spec/facter/resolvers/solaris/zfs_resolver_spec.rb
  spec/facter/resolvers/solaris/zone_resolver_spec.rb
  spec/facter/resolvers/solaris/zpool_resolver_spec.rb
Labels: maintenance

#471 (FACT-2553) Quote special string in YAML format
  .rubocop_todo.yml
  lib/facts/windows/networking/primary.rb
  lib/framework/formatters/yaml_fact_formatter.rb
  lib/resolvers/windows/ffi/network_utils.rb
  lib/resolvers/windows/networking_resolver.rb
  lib/resolvers/windows/virtualization_resolver.rb
  spec/facter/facts/windows/fips_enabled_spec.rb
  spec/facter/facts/windows/networking/primary_spec.rb
  spec/facter/resolvers/utils/windows/network_utils_spec.rb
  spec/facter/resolvers/windows/networking_resolver_spec.rb
  spec/facter/resolvers/windows/virtualization_resolver_spec.rb
  spec/framework/formatters/yaml_fact_formatter_spec.rb
  spec/mocks/win32ole_mock.rb
Labels: feature

#497 (FACT-2599) Run GitHub Actions on Ubuntu 16 and Osx 10
  .github/actions/presuite.rb
  .github/actions/presuite.sh
  .github/workflows/ci.yml
Labels: feature

#498 (FACT-2420) enable verify_partial_doubles in rspec
  spec/facter/resolvers/aix/ffi_helper_spec.rb
  spec/facter/resolvers/bsd/ffi_helper_spec.rb
  spec/facter/resolvers/windows/fips_resolver_spec.rb
  spec/facter/resolvers/windows/netkvm_resolver_spec.rb
  spec/facter/resolvers/windows/networking_resolver_spec.rb
  spec/facter/resolvers/windows/product_release_resolver_spec.rb
  spec/mocks/ffi_mock.rb
  spec/mocks/win32_mock.rb
  spec/spec_helper.rb
Labels: maintenance

#499 (FACT-2582) Date and Time in external YAML fact is not loaded
  lib/custom_facts/util/normalization.rb
  lib/custom_facts/util/parser.rb
  spec/custom_facts/util/parser_spec.rb
  spec/fixtures/external_fact_yaml
  spec/fixtures/external_fact_yaml_date
  spec/fixtures/external_fact_yaml_no_zone
Labels: bugfix

#500 (FACT-2531) Fix for tests/facts/validate_file_system_size_bytes.rb
  lib/facts/debian/architecture.rb
  lib/facts/linux/os/architecture.rb
  lib/facts/rhel/os/release.rb
  lib/resolvers/aix/mountpoints.rb
  lib/resolvers/mountpoints_resolver.rb
  lib/resolvers/processors_resolver.rb
  spec/facter/facts/debian/os/architecture_spec.rb
  spec/facter/facts/linux/os/architecture_spec.rb
  spec/facter/facts/rhel/os/release_spec.rb
  spec/facter/resolvers/mountpoints_resolver_spec.rb
  spec/facter/resolvers/processors_resolver_spec.rb
  spec/fixtures/cpuinfo_wo_physical_id
  spec/fixtures/mount
Labels: bugfix

#501 (FACT-2613) Migrate unit tests to github actions
  .github/workflows/acceptance_tests.yml
  .github/workflows/checks.yaml
  .github/workflows/unit_tests.yaml
  .travis.yml
  facter.gemspec
  spec/custom_facts/util/parser_spec.rb
  spec/facter/resolvers/windows/memory_resolver_spec.rb
Labels: maintenance

#507 (FACT-2533) Fix for tests/facts/partitions.rb
  lib/resolvers/partitions.rb
  spec/facter/resolvers/partitions_spec.rb
  spec/fixtures/blkid_output
Labels: bugfix

#508 (FACT-2613-coverage) Add code coverage in github action
  .github/workflows/acceptance_tests.yml
  .github/workflows/checks.yaml
  .github/workflows/rtc.yml
  .github/workflows/unit_tests.yaml
  README.md
Labels: maintenance

#509 (maint) Generate CHANGELOG for 4.0.21 release
  CHANGELOG.md
Labels: maintenance

#510 (maint) Fix networking linux for non-root users
  lib/resolvers/networking_linux_resolver.rb
  spec/facter/resolvers/networking_linux_resolver_spec.rb
Labels: maintenance

#512 (FACT-2525) Fix for tests/options/color.rb
  .github/workflows/acceptance_tests.yml
  lib/framework/core/options/option_store.rb
  lib/framework/logging/logger.rb
  spec/framework/core/options/option_store_spec.rb
  spec/framework/logging/logger_spec.rb
Labels: bugfix

#511 (FACT-2183) Add Solaris's uptime legacy facts
  lib/facts/solaris/system_uptime/days.rb
  lib/facts/solaris/system_uptime/hours.rb
  lib/facts/solaris/system_uptime/seconds.rb
  lib/facts/solaris/system_uptime/uptime.rb
  spec/facter/facts/solaris/system_uptime/days_spec.rb
  spec/facter/facts/solaris/system_uptime/hours_spec.rb
  spec/facter/facts/solaris/system_uptime/seconds_spec.rb
  spec/facter/facts/solaris/system_uptime/uptime_spec.rb
Labels: feature

#513 (FACT-2532) Add Aix nim_type fact
  lib/facts/aix/nim_type.rb
  lib/resolvers/aix/nim.rb
  spec/facter/facts/aix/nim_type_spec.rb
  spec/facter/resolvers/aix/nim_spec.rb
  spec/fixtures/niminfo_nim_configuration
  spec/fixtures/niminfo_w_wrong_nim_configuration
  spec/fixtures/niminfo_wo_nim_configuration
Labels: feature

#515 (FACT-2615) Add Solaris mountpoints fact
  lib/facts/solaris/mountpoints.rb
  spec/facter/facts/solaris/mountpoints_spec.rb
Labels: feature

#514 (FACT-2521) Fix for tests/external_facts/external_fact_overrides_custom_fact_with_10000_weight_or_less.rb
  lib/custom_facts/util/collection.rb
  lib/custom_facts/util/directory_loader.rb
  lib/custom_facts/util/fact.rb
  lib/custom_facts/util/resolution.rb
  spec/custom_facts/util/collection_spec.rb
  spec/custom_facts/util/directory_loader_spec.rb
  spec/custom_facts/util/resolution_spec.rb
Labels: bugfix

#517 (FACT-2522) Fix for tests/external_facts/fact_directory_precedence.rb
  lib/custom_facts/util/config.rb
  spec/custom_facts/util/config_spec.rb
Labels: bugfix

#518 (FACT-2523) Fix for tests/external_facts/non_root_users_default_external_fact_directory.rb
  lib/custom_facts/util/config.rb
  spec/custom_facts/util/config_spec.rb
Labels: bugfix

#520 (FACT-2602) Add docker/Lxc resolver for Linux
  lib/facts/linux/hypervisors.rb
  lib/facts/linux/virtual.rb
  lib/resolvers/docker_lxc.rb
  spec/facter/facts/linux/hypervisors_spec.rb
  spec/facter/facts/linux/virtual_spec.rb
  spec/facter/resolvers/docker_lxc_spec.rb
  spec/fixtures/cgroup_file
  spec/fixtures/docker_cgroup
  spec/fixtures/lxc_cgroup
Labels: feature

#521 (FACT-2603) Detect virtual on GCE vms
  lib/facts/linux/virtual.rb
  spec/facter/facts/linux/virtual_spec.rb
Labels: feature

#522 (FACT-2617) Fix for tests/external_facts/external_fact_stderr_messages_output_to_stderr.rb
  lib/facter.rb
  lib/framework/cli/cli_launcher.rb
  lib/framework/core/file_loader.rb
  lib/framework/logging/logger.rb
  lib/framework/logging/logger_helper.rb
  lib/framework/logging/multilogger.rb
  spec/facter/util/file_helper_spec.rb
  spec/framework/core/fact/internal/internal_fact_manager_spec.rb
  spec/framework/logging/logger_spec.rb
Labels: bugfix

#524 (maint) Update change-log for release 4.0.22
  CHANGELOG.md
Labels: maintenance

#527 (FACT-2631) Trace is not working as expected
  lib/framework/core/fact_loaders/external_fact_loader.rb
  lib/framework/core/options/option_store.rb
  spec/framework/core/options/option_store_spec.rb
Labels: bugfix

#528 (FACT-2632) Log error message if we encounter exceptions while loading custom facts files
  lib/custom_facts/util/loader.rb
Labels: bugfix

#529 (maint) Change log for Facter 4.0.23
  CHANGELOG.md
  facter.gemspec
Labels: maintenance

#525 (FACT-2605) Add vmware resolver
  lib/facts/linux/virtual.rb
  lib/resolvers/vmware.rb
  spec/facter/facts/linux/virtual_spec.rb
  spec/facter/resolvers/vmware_spec.rb
Labels: feature

#523 (FACT-2604) Add virt-what resolver
  lib/facts/linux/virtual.rb
  lib/resolvers/virt_what.rb
  spec/facter/facts/linux/virtual_spec.rb
  spec/facter/resolvers/virt_what_spec.rb
  spec/fixtures/proc_self_status
  spec/fixtures/virt-what-content
Labels: feature

#537 (FACT-2636) Set external as fact_type for environment variable facts.
  lib/custom_facts/util/loader.rb
  spec/custom_facts/util/loader_spec.rb
Labels: bugfix

#538 (maint) Add changelog
  CHANGELOG.md
Labels: maintenance
