Repository puppetlabs/facter-ng, pull requests merged in 2020-04, with the labels that each got.

#425 (FACT-2511) Remove file logger
  lib/framework/logging/logger.rb
  spec/framework/logging/logger_spec.rb
Labels: bugfix

#427 (maint) Bump version to 4.0.14
  VERSION
Labels: maintenance

#428 (maint) Revert for version bump
  VERSION
Labels: maintenance

#416 (FACT-2501) Fix RSpec/ContextWording offences
  .rubocop_todo.yml
  spec/custom_facts/core/execution/posix_spec.rb
  spec/custom_facts/core/execution/windows_spec.rb
  spec/custom_facts/shared_contexts/platform.rb
  spec/custom_facts/util/parser_spec.rb
  spec/facter/fact_filter_spec.rb
  spec/facter/facter_spec.rb
  spec/facter/facts/macosx/is_virtual_spec.rb
  spec/facter/resolvers/solaris/current_zone_resolver_spec.rb
  spec/facter/resolvers/solaris/solaris_release_resolver_spec.rb
  spec/facter/resolvers/solaris/zfs_resolver_spec.rb
  spec/facter/resolvers/solaris/zone_resolver_spec.rb
  spec/facter/resolvers/solaris/zpool_resolver_spec.rb
  spec/facter/resolvers/ssh_resolver_spec.rb
  spec/facter/resolvers/utils/windows/network_utils_spec.rb
  spec/framework/config/config_reader_spec.rb
  spec/framework/core/fact_loaders/external_fact_loader_spec.rb
  spec/framework/core/options_spec.rb
  spec/framework/formatters/legacy_fact_formatter_spec.rb
Labels: maintenance

#411 (maint) Remove LegacyFacter.log_exception calls
  .rubocop.yml
  lib/custom_facts/util/collection.rb
  lib/custom_facts/util/loader.rb
  lib/custom_facts/util/parser.rb
  lib/facter.rb
  spec/custom_facts/util/collection_spec.rb
  spec/custom_facts/util/loader_spec.rb
Labels: maintenance

#419 (FACT-2504) Fix RSpec/MultipleExpectations offences
  .rubocop_todo.yml
  lib/resolvers/windows/networking_resolver.rb
  spec/custom_facts/core/aggregate_spec.rb
  spec/custom_facts/core/directed_graph_spec.rb
  spec/custom_facts/core/execution/fact_manager_spec.rb
  spec/custom_facts/core/execution/posix_spec.rb
  spec/custom_facts/core/execution/windows_spec.rb
  spec/custom_facts/core/resolvable_spec.rb
  spec/custom_facts/core/suitable_spec.rb
  spec/custom_facts/util/collection_spec.rb
  spec/custom_facts/util/confine_spec.rb
  spec/custom_facts/util/directory_loader_spec.rb
  spec/custom_facts/util/fact_spec.rb
  spec/custom_facts/util/loader_spec.rb
  spec/custom_facts/util/normalization_spec.rb
  spec/custom_facts/util/parser_spec.rb
  spec/custom_facts/util/resolution_spec.rb
  spec/facter/facter_spec.rb
  spec/facter/facts/aix/hypervisors/lpar_spec.rb
  spec/facter/facts/aix/hypervisors/wpar_spec.rb
  spec/facter/facts/debian/os/family_spec.rb
  spec/facter/facts/macosx/kernelmajversion_spec.rb
  spec/facter/facts/macosx/memory/swap/used_spec.rb
  spec/facter/facts/macosx/memory/system/used_spec.rb
  spec/facter/facts/solaris/os/release_spec.rb
  spec/facter/facts/windows/memory/system/used_spec.rb
  spec/facter/facts/windows/networking/fqdn_spec.rb
  spec/facter/facts/windows/os/release_spec.rb
  spec/facter/query_parser_spec.rb
  spec/facter/resolvers/aix/ffi_helper_spec.rb
  spec/facter/resolvers/lpar_resolver_spec.rb
  spec/facter/resolvers/windows/networking_resolver_spec.rb
  spec/facter/resolvers/windows/processors_resolver_spec.rb
  spec/facter/resolvers/windows/uptime_resolver_spec.rb
  spec/facter/resolvers/wpar_resolver_spec.rb
  spec/framework/config/block_list_spec.rb
  spec/framework/config/config_reader_spec.rb
  spec/framework/core/fact/external/external_fact_manager_spec.rb
  spec/framework/core/fact_loaders/external_fact_loader_spec.rb
  spec/framework/core/fact_loaders/fact_loader_spec.rb
  spec/framework/core/options/options_validator_spec.rb
  spec/framework/detector/os_detector_spec.rb
Labels: maintenance

#429 (FACT-2499) Facts with aliases are resolved only once
  .rubocop_todo.yml
  lib/framework/core/fact/internal/internal_fact_manager.rb
  spec/facter/facter_spec.rb
  spec/framework/core/fact/internal/internal_fact_manager_spec.rb
  spec/framework/core/options/options_validator_spec.rb
Labels: bugfix

#423 (maint) Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: maintenance

#426 (FACT-2506) Generate changelog for release
  CHANGELOG.md
  Gemfile
  Rakefile
Labels: maintenance

#439 (FACT-2541) Add TYPE for legacy facts
  lib/facts/el/processor.rb
  lib/facts/el/sshalgorithmkey.rb
  lib/facts/el/sshfp_algorithm.rb
  lib/facts/macosx/sshalgorithmkey.rb
  lib/facts/macosx/sshfp_algorithm.rb
  lib/facts/sles/processor.rb
  lib/facts/sles/sshalgorithmkey.rb
  lib/facts/sles/sshfp_algorithm.rb
  lib/facts/windows/ipaddress6_interfaces.rb
  lib/facts/windows/ipaddress_interfaces.rb
  lib/facts/windows/macaddress_interfaces.rb
  lib/facts/windows/mtu_interfaces.rb
  lib/facts/windows/netmask6_interfaces.rb
  lib/facts/windows/netmask_interfaces.rb
  lib/facts/windows/network6_interfaces.rb
  lib/facts/windows/network_interfaces.rb
  lib/facts/windows/processor.rb
  lib/facts/windows/scope6_interfaces.rb
  lib/framework/core/fact_loaders/internal_fact_loader.rb
Labels: feature

#434 (FACT-2513) Updated how option aliases are displayed
  lib/framework/cli/cli.rb
Labels: bugfix

#435 (FACT-2535) Allow interpolation of Facter.fact('fact_name')
  lib/models/resolved_fact.rb
  spec/facter/facter_spec.rb
  spec/facter/model/resolved_fact_spec.rb
Labels: feature

#422 (FACT-2477) Collect facts from alternative sources
  lib/facts/debian/lsbdistcodename.rb
  lib/facts/debian/lsbdistdescription.rb
  lib/facts/debian/lsbdistid.rb
  lib/facts/debian/lsbdistrelease.rb
  lib/facts/debian/os/distro/codename.rb
  lib/facts/debian/os/distro/description.rb
  lib/facts/debian/os/distro/id.rb
  lib/facts/debian/os/distro/release.rb
  spec/facter/facts/debian/lsbdistcodename_spec.rb
  spec/facter/facts/debian/lsbdistdescription_spec.rb
  spec/facter/facts/debian/lsbdistid_spec.rb
  spec/facter/facts/debian/lsbdistrelease_spec.rb
  spec/facter/facts/debian/os/distro/codename_spec.rb
  spec/facter/facts/debian/os/distro/description_spec.rb
  spec/facter/facts/debian/os/distro/id_spec.rb
  spec/facter/facts/debian/os/distro/release_spec.rb
  spec/framework/core/fact_loaders/internal_fact_loader_spec.rb
Labels: feature

#440 (maint) Updated CHANGELOG.md
  CHANGELOG.md
Labels: maintenance

#442 (FACT-2528) Fix for tests/facts/ssh_key.rb
  lib/framework/parsers/query_parser.rb
  spec/facter/query_parser_spec.rb
Labels: bugfix

#441 (FACT-2538) Don't save core and legacy facts in collection if they have no value
  lib/models/fact_collection.rb
  spec/facter/model/fact_collection_spec.rb
Labels: bugfix

#431 (FACT-2480) Implement Facter::FileUtil for safe read of files
  .rubocop_todo.yml
  lib/custom_facts/util/parser.rb
  lib/custom_facts/version.rb
  lib/framework/core/file_loader.rb
  lib/resolvers/aix/filesystem_resolver.rb
  lib/resolvers/debian_version.rb
  lib/resolvers/disk_resolver.rb
  lib/resolvers/dmi_resolver.rb
  lib/resolvers/filesystems_resolver.rb
  lib/resolvers/fips_enabled_resolver.rb
  lib/resolvers/hostname_resolver.rb
  lib/resolvers/load_averages_resolver.rb
  lib/resolvers/memory_resolver.rb
  lib/resolvers/mountpoints_resolver.rb
  lib/resolvers/os_release_resolver.rb
  lib/resolvers/partitions.rb
  lib/resolvers/processors_resolver.rb
  lib/resolvers/selinux_resolver.rb
  lib/resolvers/solaris/filesystems_resolver.rb
  lib/resolvers/ssh_resolver.rb
  lib/util/file_helper.rb
  spec/custom_facts/util/parser_spec.rb
  spec/facter/resolvers/aix/filesystem_resolver_spec.rb
  spec/facter/resolvers/debian_version_spec.rb
  spec/facter/resolvers/disk_resolver_spec.rb
  spec/facter/resolvers/dmi_resolver_spec.rb
  spec/facter/resolvers/filesystems_resolver_spec.rb
  spec/facter/resolvers/fips_enabled_resolver_spec.rb
  spec/facter/resolvers/hostname_resolver_spec.rb
  spec/facter/resolvers/load_averages_resolver_spec.rb
  spec/facter/resolvers/memory_resolver_spec.rb
  spec/facter/resolvers/mountpoints_resolver_spec.rb
  spec/facter/resolvers/os_release_resolver_spec.rb
  spec/facter/resolvers/partitions_spec.rb
  spec/facter/resolvers/processors_resolver_spec.rb
  spec/facter/resolvers/selinux_resolver_spec.rb
  spec/facter/resolvers/solaris/filesystem_resolver_spec.rb
  spec/facter/resolvers/ssh_resolver_spec.rb
  spec/facter/util/file_helper_spec.rb
Labels: maintenance

#433 (FACT-2233) Add AIX partitons fact
  lib/facts/aix/partitions.rb
  lib/resolvers/aix/partitions.rb
  lib/resolvers/aix/utils/odm_query.rb
  spec/facter/facts/aix/partitions_spec.rb
  spec/facter/resolvers/aix/partitions_spec.rb
  spec/facter/resolvers/utils/aix/odm_query_spec.rb
  spec/fixtures/lslv_output
  spec/fixtures/partitions_cudv_query
Labels: feature

#424 (FACT-2330) Add ssh fact for Windows OpenSSH feature
  .rubocop_todo.yml
  lib/facts/windows/ssh.rb
  lib/resolvers/ssh_resolver.rb
  lib/resolvers/utils/ssh_helper.rb
  lib/resolvers/windows/ssh.rb
  spec/facter/facts/windows/ssh_spec.rb
  spec/facter/resolvers/ssh_resolver_spec.rb
  spec/facter/resolvers/utils/ssh_helper_spec.rb
  spec/facter/resolvers/windows/ssh_spec.rb
Labels: feature

#453 (FACT-2560) Fix for tests/no_errors_on_stderr.rb
  lib/facts_utils/uptime_parser.rb
  spec/facter/facts_utils/uptime_parser_spec.rb
Labels: maintenance

#454 (maint) Fix fact blocking
  lib/framework/core/options.rb
  lib/framework/core/options/config_file_options.rb
  lib/framework/core/options/option_store.rb
Labels: maintenance

#457 (maint) Improve SshHelper tests
  spec/facter/resolvers/utils/ssh_helper_spec.rb
Labels: maintenance

#458 (FACT-2562) Correctly load custom and external fact directories
  lib/facter.rb
  lib/framework/core/fact_loaders/external_fact_loader.rb
  spec/facter/facter_spec.rb
Labels: bugfix

#465 (maint) Add commit message check
  .github/PULL_REQUEST_TEMPLATE.md
  .travis.yml
  Rakefile
Labels: maintenance

#464 (maint) Facter 4.0.17 CHANGELOG.md
  CHANGELOG.md
Labels: maintenance

#455 (FACT-2559) Fix Facter.debugging? call when Facter not fully loaded
  lib/framework/logging/logger.rb
  lib/util/file_helper.rb
  spec/facter/util/file_helper_spec.rb
  spec/framework/logging/logger_spec.rb
Labels: bugfix

#443 (FACT-2564) Add support for zpool_featureflags and fix zpool_version
  lib/facts/solaris/zpool_featureflags.rb
  lib/resolvers/solaris/zpool_resolver.rb
  spec/facter/facts/solaris/zpool_featureflags_spec.rb
  spec/facter/resolvers/solaris/zpool_resolver_spec.rb
  spec/fixtures/zpool-with-featureflags
Labels: community, feature

#456 (FACT-2553) remove double backslashes from windows path
  .rubocop_todo.yml
  lib/framework/formatters/legacy_fact_formatter.rb
  lib/framework/formatters/yaml_fact_formatter.rb
  spec/framework/formatters/legacy_fact_formatter_spec.rb
  spec/framework/formatters/yaml_fact_formatter_spec.rb
Labels: bugfix

#430 (Fact 2486) Add facts cache
  .rubocop.yml
  .rubocop_todo.yml
  block_groups.conf
  fact_groups.conf
  lib/custom_facts/util/config.rb
  lib/facter.rb
  lib/framework/cli/cli.rb
  lib/framework/config/block_list.rb
  lib/framework/config/fact_groups.rb
  lib/framework/core/cache_manager.rb
  lib/framework/core/fact_manager.rb
  lib/framework/core/file_loader.rb
  lib/framework/core/options/config_file_options.rb
  lib/framework/core/options/option_store.rb
  lib/models/resolved_fact.rb
  spec/facter/cache_manager_spec.rb
  spec/facter/facter_spec.rb
  spec/facter/model/resolved_fact_spec.rb
  spec/framework/config/block_list_spec.rb
  spec/framework/config/fact_groups_spec.rb
  spec/framework/core/fact_manager_spec.rb
  spec/framework/core/options/option_store_spec.rb
Labels: feature

#466 (FACT-2565) Debian development versions causes fatal error when resolving os.release
  lib/facts/debian/os/distro/release.rb
  lib/facts/debian/os/release.rb
  lib/framework/core/fact/internal/internal_fact_manager.rb
  spec/facter/facts/debian/os/distro/release_spec.rb
  spec/facter/facts/debian/os/release_spec.rb
  spec/framework/core/fact/internal/internal_fact_manager_spec.rb
Labels: bugfix

#467 (FACT-2570) Use Facter options to store custom and external facts
  lib/custom_facts/core/legacy_facter.rb
  lib/custom_facts/util/config.rb
  lib/custom_facts/util/loader.rb
  lib/facter.rb
  lib/framework/core/fact_loaders/external_fact_loader.rb
  lib/framework/core/options.rb
  lib/framework/core/options/config_file_options.rb
  lib/framework/core/options/option_store.rb
  spec/custom_facts/util/config_spec.rb
  spec/custom_facts/util/loader_spec.rb
  spec/facter/facter_spec.rb
  spec/framework/core/options/option_store_spec.rb
Labels: bugfix

#474 (maint) Remove rubycritic from CI
  .travis.yml
Labels: maintenance

#470 (FACT-2555)Create OS hierarchy and mechanism for loading it
  .rubocop_todo.yml
  lib/framework/core/fact_loaders/class_discoverer.rb
  lib/framework/core/file_loader.rb
  lib/framework/detector/os_detector.rb
  lib/framework/detector/os_hierarchy.rb
  lib/framework/logging/logger.rb
  lib/resolvers/redhat_release_resolver.rb
  lib/resolvers/suse_release_resolver.rb
  os_hierarchy.json
  spec/facter/resolvers/redhat_release_resolver_spec.rb
  spec/facter/resolvers/suse_relese_resolver_spec.rb
  spec/fixtures/broken_os_hierarchy
  spec/fixtures/os_hierarchy
  spec/framework/detector/os_detector_spec.rb
  spec/framework/detector/os_hierarchy_spec.rb
  spec/framework/logging/logger_spec.rb
Labels: feature

#475 (maint) Move commit rake task from Rakefile to its own file.
  .travis.yml
  Rakefile
  tasks/commits.rake
Labels: maintenance

#476 (maint) remove RSpec format documentation
  .rspec
Labels: maintenance

#472 (FACT-2585) Mountpoints fact returns ASCI-8BIT instead of UTF-8 in some cases
  lib/resolvers/utils/filesystem_helper.rb
  spec/facter/resolvers/mountpoints_resolver_spec.rb
  spec/facter/resolvers/utils/macosx/filesystem_helper_spec.rb
Labels: bugfix

#480 (maint) Update Changelog with Facter 4.0.18
  CHANGELOG.md
Labels: maintenance

#481 (maint) Build absolute path for os hierarchy json.
  lib/framework/detector/os_hierarchy.rb
  spec/framework/detector/os_hierarchy_spec.rb
Labels: maintenance

#478 (FACT-2542) Refactored some facter.rb unit tests
  lib/facts/debian/os/distro/codename.rb
  spec/facter/facter_spec.rb
Labels: maintenance

#482 (maint) Changelog update for 4.0.19
  CHANGELOG.md
Labels: maintenance

#449 (FACT-2530) Fix for tests/facts/os_processors_and_kernel.rb
  lib/facts/debian/os/distro/release.rb
  lib/facts/debian/os/release.rb
  lib/resolvers/os_release_resolver.rb
  spec/facter/facts/debian/os/distro/release_spec.rb
  spec/facter/facts/debian/os/release_spec.rb
  spec/facter/resolvers/os_release_resolver_spec.rb
  spec/fixtures/debian_os_release
Labels: bugfix

#460 Add support for *BSD load averages
  .rubocop_todo.yml
  lib/facts/bsd/load_averages.rb
  lib/resolvers/bsd/ffi/ffi_helper.rb
  lib/resolvers/bsd/load_averages_resolver.rb
  spec/facter/facts/bsd/load_averages_spec.rb
  spec/facter/resolvers/bsd/ffi_helper_spec.rb
  spec/facter/resolvers/bsd/load_averages_resolver_spec.rb
Labels: community, feature

#461 Fix os.family fact on *BSD
  lib/facts/bsd/os/family.rb
  spec/facter/facts/bsd/os/family_spec.rb
Labels: community, feature

#462 Add *BSD kernelversion and kernelmajversion facts
  lib/facts/bsd/kernelmajversion.rb
  lib/facts/bsd/kernelversion.rb
  spec/facter/facts/bsd/kernelmajversion_spec.rb
  spec/facter/facts/bsd/kernelversion_spec.rb
Labels: community, feature

#484 (FACT-2590) No facts are displayed on Redhat 5 and Centos6
  lib/framework/detector/os_detector.rb
  os_hierarchy.json
  spec/framework/detector/os_detector_spec.rb
Labels: bugfix
